### ISSUE TITLE
attempt to call field 'open' (a nil value)

### ISSUE THREAD

**Issue by SergeySpirin** [ellisonleao/carbon-now.nvim#15]
```
Error executing Lua callback: ...ite/pack/packer/start/carbon-now.nvim/lua/carbon-now.lua:144: attempt to call field 'open' (a nil value)
stack traceback:
        ...ite/pack/packer/start/carbon-now.nvim/lua/carbon-now.lua:144: in function 'create_snapshot'
        ...ite/pack/packer/start/carbon-now.nvim/lua/carbon-now.lua:149: in function <...ite/pack/packer/start/carbon-now.nvim/lua/carbon-now.lua:148>
```

![CleanShot 2024-06-08 at 10  01 07](https://github.com/ellisonleao/carbon-now.nvim/assets/76700939/6d9a874d-28f5-4ce4-bedc-c099a743ad39)

**Comment by ellisonleao** [comment]
hey @SergeySpirin what neovim version are you using?

**Comment by pixlmint** [comment]
@ellisonleao I am getting the error as well on version 0.9.5, LuaJIT Version 2.1.1703358377

**Comment by ellisonleao** [comment]
hey @pixlmint @SergeySpirin please update neovim to latest stable. That should fix the issue
